[package]
name = "chess"
version = "0.0.1"
authors = ["Jordan Bray <jordanbray@gmail.com>"]
description = "Fast Chess Move Generator"

homepage = "https://github.com/jordanbray/chess"
repository = "https://github.com/jordanbray/chess"
readme = "README.md"
keywords = ["chess", "move", "generator"]
license = "LGPL-3.0+"

[profile.release]
opt-level = 3
debug = false

[profile.dev]
opt-level = 3
debug = true


[dependencies]
rand = "0.3"
lazy_static = "0.1.*"
time = "0.1.35"

